using System.Drawing.Drawing2D;

namespace YacaPluginSwitcher.UI;

internal static class ProfessionalVisuals
{
    private static readonly HashSet<Control> Hooked = [];
    public static void Apply(Control root){HookTree(root);root.ControlAdded-=RootControlAdded;root.ControlAdded+=RootControlAdded;RemoveEmptyContentHeader(root);root.Invalidate(true);}
    private static void RootControlAdded(object? sender,ControlEventArgs e){HookTree(e.Control!);RemoveEmptyContentHeader(e.Control!);}
    private static void HookTree(Control control){if(Hooked.Add(control)){control.ControlAdded+=RootControlAdded;if(control is Button b)StyleButton(b);else if(control is Panel p)StylePanel(p);else if(control is Label l)StyleLabel(l);}foreach(Control child in control.Controls)HookTree(child);}
    private static void RemoveEmptyContentHeader(Control root){foreach(Control child in root.Controls){if(child is not TableLayoutPanel table||table.RowCount!=2||table.RowStyles.Count<2||table.RowStyles[0].SizeType!=SizeType.Absolute||table.RowStyles[0].Height>50)continue;if(table.Controls.Count==0||table.Controls[0]is not Label label||!string.IsNullOrWhiteSpace(label.Text))continue;table.RowStyles[0].Height=0;label.Visible=false;table.Padding=Padding.Empty;}foreach(Control child in root.Controls)RemoveEmptyContentHeader(child);}
    private static void StylePanel(Panel panel){if(panel.BackColor==Color.FromArgb(13,14,18))panel.BackColor=Theme.Sidebar;if(panel.Parent is TableLayoutPanel parent&&(parent.ColumnCount==3||parent.ColumnCount==2)){panel.Paint-=CardPaint;panel.Paint+=CardPaint;}if(panel.Controls.Count==1&&panel.Controls[0]is PictureBox){panel.Paint-=LogoCardPaint;panel.Paint+=LogoCardPaint;}}
    private static void StyleLabel(Label label){if(label.Text.Contains("YACA",StringComparison.OrdinalIgnoreCase)&&label.Font.Size>=18)label.ForeColor=Theme.Foreground;if(label.Text.Contains("PLUGIN SWITCHER",StringComparison.OrdinalIgnoreCase))label.ForeColor=Theme.BrandGold;if(label.Text.Contains("by ViP3R_76",StringComparison.OrdinalIgnoreCase))label.ForeColor=Theme.Accent;label.BackColor=Color.Transparent;}
    private static void StyleButton(Button button){if(button.Tag is not null)return;var text=button.Text?.Trim()??string.Empty;button.Tag=text;button.FlatStyle=FlatStyle.Flat;button.FlatAppearance.BorderSize=0;button.UseVisualStyleBackColor=false;button.BackColor=Color.Transparent;button.ForeColor=Theme.Foreground;button.Cursor=Cursors.Hand;button.Paint+=ButtonPaint;button.MouseEnter+=(_,_)=>button.Invalidate();button.MouseLeave+=(_,_)=>button.Invalidate();}
    private static void ButtonPaint(object? sender,PaintEventArgs e){if(sender is not Button button||button.Tag is not string text)return;e.Graphics.SmoothingMode=SmoothingMode.AntiAlias;e.Graphics.Clear(button.BackColor);var isAction=button.Parent is TableLayoutPanel parent&&parent.ColumnCount==3&&parent.RowCount==1&&button.Height>=120;var isNav=!isAction&&button.Height<=55;if(isAction){DrawActionButton(e.Graphics,button,text);return;}if(isNav){DrawNavButton(e.Graphics,button,text);return;}DrawStandardButton(e.Graphics,button,text);}
    private static void DrawNavButton(Graphics g,Button button,string text){var selected=button.BackColor==Theme.NavSelected||button.ForeColor==Theme.BrandGold;var rect=new Rectangle(0,1,Math.Max(0,button.Width-2),Math.Max(0,button.Height-3));if(selected){using var bg=new SolidBrush(Theme.NavSelected);g.FillRoundedRectangle(bg,rect,8);using var accent=new SolidBrush(Theme.Accent);g.FillRoundedRectangle(accent,new Rectangle(0,7,3,Math.Max(0,button.Height-14)),2);}var icon=NavIconFor(text);IconPainter.Draw(g,icon,new Rectangle(13,(button.Height-22)/2,22,22),selected?Theme.BrandGold:Theme.Foreground,1.8F);using var brush=new SolidBrush(selected?Theme.BrandGold:Theme.Foreground);using var font=new Font("Segoe UI Semibold",10F);var clean=text.Replace("⌂","").Replace("↻","").Replace("⇄","").Replace("＋","").Trim();g.DrawString(clean,font,brush,48,(button.Height-font.Height)/2f);}
    private static void DrawActionButton(Graphics g,Button button,string text){var accent=text.Contains("BACKUP",StringComparison.OrdinalIgnoreCase)?Theme.BrandGold:Theme.Accent;var rect=new Rectangle(0,1,Math.Max(0,button.Width-2),Math.Max(0,button.Height-3));using var bg=new LinearGradientBrush(rect,Theme.Surface,Color.FromArgb(13,14,18),LinearGradientMode.Vertical);g.FillRectangle(bg,rect);using var border=new Pen(accent,1.4F);g.DrawRoundedRectangle(border,rect,10);DrawWaves(g,rect,accent);var icon=text.Contains("WECHSELN",StringComparison.OrdinalIgnoreCase)?ActionIcon.Switch:text.Contains("BACKUP",StringComparison.OrdinalIgnoreCase)?ActionIcon.Backup:ActionIcon.Updater;var iconTop=Math.Max(24,button.Height/2-58);IconPainter.DrawAction(g,icon,new Rectangle((button.Width-72)/2,iconTop,72,72),accent);using var titleFont=new Font("Segoe UI Semibold",12.5F);using var subFont=new Font("Segoe UI",9F);var title=text.Split('\n')[0].Replace("⇄","").Replace("+","").Replace("⇩","").Trim();var subtitle=text.Contains('\n')?text[(text.IndexOf('\n')+1)..]:string.Empty;using var titleBrush=new SolidBrush(Theme.Foreground);using var subBrush=new SolidBrush(Theme.SecondaryForeground);var center=button.Height/2f;var ts=g.MeasureString(title,titleFont);g.DrawString(title,titleFont,titleBrush,(button.Width-ts.Width)/2f,center+18);var ss=g.MeasureString(subtitle,subFont);g.DrawString(subtitle,subFont,subBrush,(button.Width-ss.Width)/2f,center+49);if(title.Contains("UPDATER",StringComparison.OrdinalIgnoreCase)){using var badge=new SolidBrush(Color.FromArgb(95,64,135));g.FillRoundedRectangle(badge,new Rectangle(button.Width-120,16,98,28),7);using var badgeFont=new Font("Segoe UI Semibold",8F);using var badgeBrush=new SolidBrush(Color.White);g.DrawString("BALD VERFÜGBAR",badgeFont,badgeBrush,button.Width-111,22);}}
    private static void DrawStandardButton(Graphics g,Button button,string text){using var bg=new SolidBrush(Theme.Control);g.FillRectangle(bg,button.ClientRectangle);using var pen=new Pen(Theme.Border,1);g.DrawRectangle(pen,0,0,button.Width-1,button.Height-1);using var brush=new SolidBrush(Theme.Foreground);using var format=new StringFormat{Alignment=StringAlignment.Center,LineAlignment=StringAlignment.Center};g.DrawString(text,button.Font,brush,new RectangleF(8,0,button.Width-16,button.Height),format);}
    private static void CardPaint(object? sender,PaintEventArgs e){if(sender is not Panel panel)return;e.Graphics.SmoothingMode=SmoothingMode.AntiAlias;using var brush=new LinearGradientBrush(panel.ClientRectangle,Theme.Surface,Color.FromArgb(12,13,17),LinearGradientMode.Vertical);e.Graphics.FillRectangle(brush,panel.ClientRectangle);var accent=panel.Parent is TableLayoutPanel parent&&parent.Controls.GetChildIndex(panel)==2?Theme.BrandGold:Theme.Accent;using var pen=new Pen(accent,1.2F);e.Graphics.DrawRoundedRectangle(pen,new Rectangle(0,0,Math.Max(0,panel.Width-1),Math.Max(0,panel.Height-1)),9);}
    private static void LogoCardPaint(object? sender,PaintEventArgs e){if(sender is not Panel panel)return;e.Graphics.SmoothingMode=SmoothingMode.AntiAlias;using var pen=new Pen(Theme.Accent,1.5F);e.Graphics.DrawRoundedRectangle(pen,new Rectangle(0,0,panel.Width-1,panel.Height-1),10);}
    private static void DrawWaves(Graphics g,Rectangle rect,Color color){using var pen=new Pen(Color.FromArgb(80,color.R,color.G,color.B),1.2F);using var path=new GraphicsPath();path.AddBezier(rect.Left+8,rect.Bottom-28,rect.Left+rect.Width/3,rect.Bottom-62,rect.Width/2,rect.Bottom+4,rect.Right-8,rect.Bottom-34);g.DrawPath(pen,path);path.Reset();path.AddBezier(rect.Left+40,rect.Bottom-12,rect.Width/3,rect.Bottom-45,rect.Width*2/3,rect.Bottom+10,rect.Right-35,rect.Bottom-20);g.DrawPath(pen,path);}
    private static NavIcon NavIconFor(string text){if(text.Contains("Aktual",StringComparison.OrdinalIgnoreCase)||text.Contains("Refresh",StringComparison.OrdinalIgnoreCase))return NavIcon.Refresh;if(text.Contains("wechsel",StringComparison.OrdinalIgnoreCase)||text.Contains("Switch",StringComparison.OrdinalIgnoreCase))return NavIcon.Switch;if(text.Contains("Backup erstellen",StringComparison.OrdinalIgnoreCase)||text.Contains("Create Backup",StringComparison.OrdinalIgnoreCase))return NavIcon.Backup;if(text.Contains("Backups",StringComparison.OrdinalIgnoreCase))return NavIcon.Backups;if(text.Contains("Konfig",StringComparison.OrdinalIgnoreCase)||text.Contains("Config",StringComparison.OrdinalIgnoreCase))return NavIcon.Settings;if(text.Contains("Info",StringComparison.OrdinalIgnoreCase)||text.Contains("About",StringComparison.OrdinalIgnoreCase))return NavIcon.Info;return NavIcon.Home;}
}

internal enum NavIcon{Home,Refresh,Switch,Backup,Backups,Settings,Info,Headset}
internal enum ActionIcon{Switch,Backup,Updater}
internal static class IconPainter
{
    public static void Draw(Graphics g,NavIcon icon,Rectangle r,Color color,float width){g.SmoothingMode=SmoothingMode.AntiAlias;using var pen=new Pen(color,width){StartCap=LineCap.Round,EndCap=LineCap.Round,LineJoin=LineJoin.Round};var cx=r.Left+r.Width/2f;var cy=r.Top+r.Height/2f;switch(icon){case NavIcon.Home:g.DrawLine(pen,r.Left+3,r.Top+10,cx,r.Top+3);g.DrawLine(pen,cx,r.Top+3,r.Right-3,r.Top+10);g.DrawRectangle(pen,r.Left+6,r.Top+10,r.Width-12,r.Height-7);break;case NavIcon.Refresh:g.DrawArc(pen,r.Left+3,r.Top+3,r.Width-6,r.Height-6,35,250);g.DrawLine(pen,r.Right-3,r.Top+6,r.Right-3,r.Top+1);break;case NavIcon.Switch:g.DrawLine(pen,r.Left+3,r.Top+7,r.Right-4,r.Top+7);g.DrawLine(pen,r.Right-8,r.Top+3,r.Right-3,r.Top+7);g.DrawLine(pen,r.Right-8,r.Top+11,r.Right-3,r.Top+7);g.DrawLine(pen,r.Right-3,r.Bottom-7,r.Left+4,r.Bottom-7);g.DrawLine(pen,r.Left+8,r.Bottom-11,r.Left+3,r.Bottom-7);g.DrawLine(pen,r.Left+8,r.Bottom-3,r.Left+3,r.Bottom-7);break;case NavIcon.Backup:g.DrawRectangle(pen,r.Left+4,r.Top+4,r.Width-8,r.Height-8);g.DrawLine(pen,cx,r.Top+7,cx,r.Bottom-7);g.DrawLine(pen,r.Left+7,cy,r.Right-7,cy);break;case NavIcon.Backups:g.DrawEllipse(pen,r.Left+4,r.Top+3,r.Width-8,6);g.DrawArc(pen,r.Left+4,r.Top+3,r.Width-8,15,0,180);g.DrawArc(pen,r.Left+4,r.Top+9,r.Width-8,15,0,180);break;case NavIcon.Settings:g.DrawEllipse(pen,r.Left+6,r.Top+6,r.Width-12,r.Height-12);for(var i=0;i<8;i++){var a=i*Math.PI/4;g.DrawLine(pen,cx+(float)Math.Cos(a)*8,cy+(float)Math.Sin(a)*8,cx+(float)Math.Cos(a)*10,cy+(float)Math.Sin(a)*10);}break;case NavIcon.Info:g.DrawEllipse(pen,r.Left+3,r.Top+3,r.Width-6,r.Height-6);g.DrawLine(pen,cx,r.Top+9,cx,r.Bottom-5);using(var b=new SolidBrush(color))g.FillEllipse(b,cx-1.5F,r.Top+6,3,3);break;case NavIcon.Headset:g.DrawArc(pen,r.Left+4,r.Top+3,r.Width-8,r.Height-5,180,180);g.DrawLine(pen,r.Left+4,cy,r.Left+4,r.Bottom-5);g.DrawLine(pen,r.Right-4,cy,r.Right-4,r.Bottom-5);break;}}
    public static void DrawAction(Graphics g,ActionIcon icon,Rectangle r,Color color){using var pen=new Pen(color,3F){StartCap=LineCap.Round,EndCap=LineCap.Round,LineJoin=LineJoin.Round};g.SmoothingMode=SmoothingMode.AntiAlias;g.DrawEllipse(pen,r.Left+2,r.Top+2,r.Width-4,r.Height-4);var cx=r.Left+r.Width/2f;var cy=r.Top+r.Height/2f;switch(icon){case ActionIcon.Switch:g.DrawLine(pen,r.Left+22,cy-10,r.Right-20,cy-10);g.DrawLine(pen,r.Right-26,cy-16,r.Right-18,cy-10);g.DrawLine(pen,r.Right-26,cy-4,r.Right-18,cy-10);g.DrawLine(pen,r.Right-22,cy+10,r.Left+20,cy+10);g.DrawLine(pen,r.Left+26,cy+4,r.Left+18,cy+10);g.DrawLine(pen,r.Left+26,cy+16,r.Left+18,cy+10);break;case ActionIcon.Backup:g.DrawLine(pen,cx,r.Top+25,cx,r.Bottom-25);g.DrawLine(pen,r.Left+25,cy,r.Right-25,cy);break;case ActionIcon.Updater:g.DrawLine(pen,cx,r.Top+25,cx,r.Bottom-30);g.DrawLine(pen,cx-12,r.Bottom-42,cx,r.Bottom-30);g.DrawLine(pen,cx+12,r.Bottom-42,cx,r.Bottom-30);break;}}
}
internal static class ProfessionalGraphicsExtensions
{
    public static void FillRoundedRectangle(this Graphics g,Brush brush,Rectangle rect,int radius){using var path=Rounded(rect,radius);g.FillPath(brush,path);}
    public static void DrawRoundedRectangle(this Graphics g,Pen pen,Rectangle rect,int radius){using var path=Rounded(rect,radius);g.DrawPath(pen,path);}
    private static GraphicsPath Rounded(Rectangle rect,int radius){var d=radius*2;var path=new GraphicsPath();path.AddArc(rect.X,rect.Y,d,d,180,90);path.AddArc(rect.Right-d,rect.Y,d,d,270,90);path.AddArc(rect.Right-d,rect.Bottom-d,d,d,0,90);path.AddArc(rect.X,rect.Bottom-d,d,d,90,90);path.CloseFigure();return path;}
}
