global using System.Collections.ObjectModel;
global using System.IO;
global using System.Text;
global using Microsoft.Win32;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Input;
global using System.Windows.Media;
global using System.Windows.Media.Imaging;
global using YacaPluginSwitcher.Core;
global using Localization = YacaPluginSwitcher.Configuration.Localization;
global using UiText = YacaPluginSwitcher.Configuration.UiText;
