using System.Globalization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Input;
using System.Windows.Media;
using YacaPluginSwitcher.Core;
using YacaPluginSwitcher.Models;

namespace YacaPluginSwitcher;

public partial class MainWindow : Window
{
    private readonly YacaService _service;
    private readonly YacaUpdaterService _updater;
    private readonly List<(string Key, Button Button)> _navButtons = [];
    private readonly List<YacaPluginInfo> _plugins = [];
    private string _activePage = "home";
    private TextBlock? _currentValue, _currentDetails, _tsStatus, _tsDescription, _backupSummary;
    private Button? _tsClose;
    private StackPanel? _versionList, _downloadedFilesPanel;
    private Border? _currentCard, _backupCard;
    private ProgressBar? _updaterProgress;
    private TextBlock? _updaterStatus, _updaterVersion, _updaterSize;
    private CancellationTokenSource? _updaterCts;
    private HashSet<string> _knownPlugins = new(StringComparer.OrdinalIgnoreCase);
    private bool _pluginBaselineInitialized;
    private System.Windows.Threading.DispatcherTimer? _flashTimer;
    private UiText Texts => Localization.Get(_service.Settings.Language);
    private bool IsGerman => Localization.Normalize(_service.Settings.Language) == Localization.German;

    public MainWindow(YacaService service)
    {
        _service = service ?? throw new ArgumentNullException(nameof(service));
        _updater = new YacaUpdaterService(_service);
        InitializeComponent(); GlobalFooterVersionText.Text = "v1.1.0"; BuildNavigation(); LoadLanguageSelector(); ShowHome();
    }

    private void BuildNavigation()
    {
        NavPanel.Children.Clear(); _navButtons.Clear(); NavPanel.Children.Add(new Separator { Margin = new Thickness(10, 0, 0, 8), Background = (Brush)FindResource("AccentSoftBrush") });
        AddNav("home", "home", "Dashboard", ShowHome); AddNav("refresh", "refresh", IsGerman ? "Aktualisieren" : "Refresh", () => RefreshActivePage(true)); AddNav("switch", "switch", IsGerman ? "YACA wechseln" : "Switch YACA", () => ShowSwitchPage()); AddNav("updater", "updater", "YACA Updater", () => ShowSwitchPage(IsGerman ? "YACA Updater: Download-Bereich geöffnet." : "YACA Updater: download area opened."));
        NavPanel.Children.Add(new Separator { Margin = new Thickness(10, 12, 0, 12), Background = (Brush)FindResource("AccentSoftBrush") }); AddNav("backup-create", "backup", IsGerman ? "Backup erstellen" : "Create Backup", () => CreateBackupFromDashboard()); AddNav("backups", "backups", IsGerman ? "Backup verwalten" : "Manage Backups", ShowBackups);
        NavPanel.Children.Add(new Separator { Margin = new Thickness(10, 12, 0, 12), Background = (Brush)FindResource("AccentSoftBrush") }); AddNav("info", "info", "Info & Links", ShowInfo); if (ExitNavText is not null) ExitNavText.Text = IsGerman ? "Beenden" : "Exit";
    }

    private void AddNav(string key, string iconKey, string text, Action action)
    {
        var content = new StackPanel { Orientation = Orientation.Horizontal, VerticalAlignment = VerticalAlignment.Center }; System.Windows.Shapes.Path? icon = null; if (DashboardIconData.TryGetValue(iconKey, out var data)) { icon = CreateIcon(data, (Brush)FindResource("ForegroundBrush"), 30, 30, 0); content.Children.Add(icon); }
        content.Children.Add(new TextBlock { Text = text, FontSize = 14, VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(12, 0, 0, 0) }); var button = new Button { Style = (Style)FindResource("NavButtonStyle"), Height = 46, Tag = key, Content = content };
        button.MouseEnter += (_, _) => { button.Background = (Brush)FindResource("NavSelectedBrush"); button.Foreground = (Brush)FindResource("GoldBrush"); button.BorderBrush = (Brush)FindResource("GoldBrush"); if (icon is not null) icon.Fill = (Brush)FindResource("GoldBrush"); }; button.MouseLeave += (_, _) => { var selected = string.Equals(_activePage, key, StringComparison.OrdinalIgnoreCase); button.Background = selected ? (Brush)FindResource("NavSelectedBrush") : Brushes.Transparent; button.Foreground = selected ? (Brush)FindResource("GoldBrush") : (Brush)FindResource("ForegroundBrush"); button.BorderBrush = selected ? (Brush)FindResource("GoldBrush") : Brushes.Transparent; if (icon is not null) icon.Fill = selected ? (Brush)FindResource("GoldBrush") : (Brush)FindResource("ForegroundBrush"); }; button.Click += (_, _) => action(); NavPanel.Children.Add(button); _navButtons.Add((key, button));
    }

    private void SetActiveNav(string key) { _activePage = key; foreach (var item in _navButtons) { var selected = item.Key.Equals(key, StringComparison.OrdinalIgnoreCase); item.Button.Background = selected ? (Brush)FindResource("NavSelectedBrush") : Brushes.Transparent; item.Button.Foreground = selected ? (Brush)FindResource("GoldBrush") : (Brush)FindResource("ForegroundBrush"); item.Button.BorderBrush = selected ? (Brush)FindResource("GoldBrush") : Brushes.Transparent; item.Button.BorderThickness = selected ? new Thickness(1) : new Thickness(0); if (item.Button.Content is StackPanel panel && panel.Children.OfType<System.Windows.Shapes.Path>().FirstOrDefault() is { } icon) icon.Fill = selected ? (Brush)FindResource("GoldBrush") : (Brush)FindResource("ForegroundBrush"); } }
    private void LoadLanguageSelector() { LanguageCombo.Items.Clear(); LanguageCombo.Items.Add(Texts.LanguageGerman); LanguageCombo.Items.Add(Texts.LanguageEnglish); LanguageCombo.SelectedIndex = IsGerman ? 0 : 1; if (ExitNavText is not null) ExitNavText.Text = IsGerman ? "Beenden" : "Exit"; }
    private void LanguageCombo_SelectionChanged(object sender, SelectionChangedEventArgs e) { if (!IsInitialized || LanguageCombo.SelectedIndex < 0) return; var language = LanguageCombo.SelectedIndex == 0 ? Localization.German : Localization.English; if (string.Equals(Localization.Normalize(_service.Settings.Language), language, StringComparison.OrdinalIgnoreCase)) return; _service.Settings.Language = language; _service.Settings.Save(); BuildNavigation(); LoadLanguageSelector(); ShowCurrentPageAfterLanguageChange(); }
    private void ShowCurrentPageAfterLanguageChange() { switch (_activePage) { case "switch": ShowSwitchPage(); break; case "backups": ShowBackups(); break; case "config": ShowConfig(); break; case "info": ShowInfo(); break; default: ShowHome(); break; } }
    private void SetGlobalStatus(string message, bool success = false) { GlobalFooterStatusText.Text = message; GlobalFooterStatusText.Foreground = (Brush)FindResource(success ? "SuccessBrush" : "ForegroundBrush"); }

    private void ShowHome() { _activePage = "home"; PageHost.Content = RenderDashboard(); SetActiveNav("home"); SetGlobalStatus(IsGerman ? "Bereit." : "Ready."); RefreshHome(); }

    private void RefreshHome(bool announce = false)
    {
        if (_activePage != "home") return; try { _plugins.Clear(); _plugins.AddRange(GetDistinctPlugins()); var notice = announce ? GetNewPluginNotice(_plugins) : null; if (!_pluginBaselineInitialized) SetPluginBaseline(_plugins); var current = _service.DetectCurrent(); UpdateCurrentInstalled(current); if (announce) FlashElement(_currentCard); var running = TeamSpeakDetector.IsRunning(); _tsStatus!.Text = running ? (IsGerman ? "GESTARTET" : "RUNNING") : (IsGerman ? "NICHT GESTARTET" : "NOT RUNNING"); _tsStatus.Foreground = running ? (Brush)FindResource("ErrorBrush") : (Brush)FindResource("GoldBrush"); _tsDescription!.Text = running ? (IsGerman ? "TeamSpeak 3 ist aktiv!\nFür einen sicheren Wechsel bitte zuerst schliessen." : "TeamSpeak 3 is active!\nFor a safe switch, please close it first.") : (IsGerman ? "TeamSpeak 3 ist nicht aktiv.\nWechsel jederzeit möglich." : "TeamSpeak 3 is not active.\nSwitching is ready."); _tsClose!.Visibility = running ? Visibility.Visible : Visibility.Collapsed; UpdateBackupSummary(_service.Backups.ListBackups().FirstOrDefault()); RenderVersionList(current); SetGlobalStatus(string.IsNullOrWhiteSpace(notice) ? (running ? Texts.TeamspeakRunning : Texts.TeamspeakStopped) : notice); } catch (Exception ex) { _service.Logger.Error($"Dashboard refresh failed: {ex}"); ShowError(Texts.ErrorUnexpected); }
    }

    private void UpdateCurrentInstalled(YacaPluginInfo? current) { _currentValue!.Text = current?.Version?.ToString() ?? (File.Exists(_service.TargetFile) ? Texts.UnknownInvalid : Texts.NotInstalled); _currentValue.Foreground = current is null ? (Brush)FindResource("WarningBrush") : (Brush)FindResource("ForegroundBrush"); if (_currentDetails is not null) _currentDetails.Text = current is null ? string.Empty : $"Build: {current.Build?.ToString(CultureInfo.InvariantCulture) ?? "—"}\nGröße: {current.FileSize.ToString("N0", CultureInfo.GetCultureInfo("de-DE"))} Bytes\nSHA-256: {current.Sha256}"; }
    private List<YacaPluginInfo> GetDistinctPlugins() { var result = new List<YacaPluginInfo>(); var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase); foreach (var p in _service.ScanPlugins()) if (seen.Add($"{p.FilePath}|{p.Sha256}")) result.Add(p); return result; }
    private string? GetNewPluginNotice(IReadOnlyList<YacaPluginInfo> plugins) { var keys = plugins.Select(p => $"{p.FilePath}|{p.Sha256}").ToHashSet(StringComparer.OrdinalIgnoreCase); if (!_pluginBaselineInitialized) { _knownPlugins = keys; _pluginBaselineInitialized = true; return null; } var added = plugins.Where(p => !_knownPlugins.Contains($"{p.FilePath}|{p.Sha256}")).ToList(); _knownPlugins = keys; return added.Count == 0 ? null : string.Format(CultureInfo.CurrentCulture, Texts.NewValidPluginFound, string.Join(", ", added.Select(p => p.DisplayName))); }
    private void SetPluginBaseline(IReadOnlyList<YacaPluginInfo> plugins) { _knownPlugins = plugins.Select(p => $"{p.FilePath}|{p.Sha256}").ToHashSet(StringComparer.OrdinalIgnoreCase); _pluginBaselineInitialized = true; }

    private void ShowSwitchPage(string? status = null)
    {
        _activePage = "switch"; SetActiveNav("switch"); var root = new Grid { Margin = new Thickness(0, 4, 0, 0) }; root.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) }); root.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) });
        var left = new Border { Background = (Brush)FindResource("SurfaceBrush"), BorderBrush = (Brush)FindResource("AccentBrush"), BorderThickness = new Thickness(1), CornerRadius = new CornerRadius(10), Padding = new Thickness(20), Margin = new Thickness(6) }; var leftPanel = new Grid(); leftPanel.RowDefinitions.Add(new RowDefinition { Height = GridLength.Auto }); leftPanel.RowDefinitions.Add(new RowDefinition { Height = new GridLength(1, GridUnitType.Star) }); leftPanel.Children.Add(CreateDashboardHeader("switch", IsGerman ? "VERFÜGBARE VERSIONEN" : "AVAILABLE VERSIONS", (Brush)FindResource("AccentBrush"))); var list = new StackPanel { Margin = new Thickness(6, 10, 6, 6) }; var scroll = new ScrollViewer { Content = list, VerticalScrollBarVisibility = ScrollBarVisibility.Auto, HorizontalScrollBarVisibility = ScrollBarVisibility.Disabled, Background = (Brush)FindResource("SurfaceBrush") }; Grid.SetRow(scroll, 1); leftPanel.Children.Add(scroll); left.Child = leftPanel; Grid.SetColumn(left, 0); root.Children.Add(left);
        var right = new Grid { Margin = new Thickness(6) }; right.RowDefinitions.Add(new RowDefinition { Height = new GridLength(1, GridUnitType.Star) }); right.RowDefinitions.Add(new RowDefinition { Height = new GridLength(1, GridUnitType.Star) });
        var updaterCard = new Border { Background = (Brush)FindResource("SurfaceBrush"), BorderBrush = (Brush)FindResource("GoldBrush"), BorderThickness = new Thickness(1), CornerRadius = new CornerRadius(10), Padding = new Thickness(20), Margin = new Thickness(0, 0, 0, 6) }; var updaterPanel = new Grid(); updaterPanel.RowDefinitions.Add(new RowDefinition { Height = GridLength.Auto }); updaterPanel.RowDefinitions.Add(new RowDefinition { Height = new GridLength(1, GridUnitType.Star) }); updaterPanel.RowDefinitions.Add(new RowDefinition { Height = GridLength.Auto }); updaterPanel.Children.Add(CreateDashboardHeader("updater", IsGerman ? "VERFÜGBARE YACA UPDATE-/DOWNLOADS" : "AVAILABLE YACA UPDATES/DOWNLOADS", (Brush)FindResource("GoldBrush")));
        var updateContent = new StackPanel { Margin = new Thickness(6, 14, 6, 6), VerticalAlignment = VerticalAlignment.Center }; _updaterVersion = new TextBlock { Text = IsGerman ? "Bereit für Updates" : "Ready for updates", FontSize = 22, FontWeight = FontWeights.Bold, Foreground = (Brush)FindResource("ForegroundBrush"), HorizontalAlignment = HorizontalAlignment.Center }; _updaterStatus = new TextBlock { Text = IsGerman ? "Neue YACA Versionen können hier heruntergeladen werden." : "New YACA versions can be downloaded here.", FontSize = 14, Foreground = (Brush)FindResource("SecondaryBrush"), TextAlignment = TextAlignment.Center, Margin = new Thickness(0, 8, 0, 12), TextWrapping = TextWrapping.Wrap }; _updaterProgress = new ProgressBar { Height = 10, Minimum = 0, Maximum = 100, Visibility = Visibility.Collapsed, Margin = new Thickness(0, 0, 0, 10) }; _updaterSize = new TextBlock { FontSize = 12, Foreground = (Brush)FindResource("SecondaryBrush"), HorizontalAlignment = HorizontalAlignment.Center }; updateContent.Children.Add(_updaterVersion); updateContent.Children.Add(_updaterStatus); updateContent.Children.Add(_updaterProgress); updateContent.Children.Add(_updaterSize); Grid.SetRow(updateContent, 1); updaterPanel.Children.Add(updateContent);
        var updateButton = new Button { Content = IsGerman ? "YACA UPDATES PRÜFEN UND HERUNTERLADEN" : "CHECK FOR YACA UPDATES AND DOWNLOAD", Height = 42, FontWeight = FontWeights.Bold, Background = (Brush)FindResource("GoldBrush"), Foreground = Brushes.Black, BorderThickness = new Thickness(0), Margin = new Thickness(6, 4, 6, 0), Cursor = Cursors.Hand }; updateButton.Click += async (_, _) => await RunUpdaterAsync(); Grid.SetRow(updateButton, 2); updaterPanel.Children.Add(updateButton); updaterCard.Child = updaterPanel; Grid.SetRow(updaterCard, 0); right.Children.Add(updaterCard);
        var filesCard = new Border { Background = (Brush)FindResource("SurfaceBrush"), BorderBrush = (Brush)FindResource("GoldBrush"), BorderThickness = new Thickness(1), CornerRadius = new CornerRadius(10), Padding = new Thickness(20), Margin = new Thickness(0, 6, 0, 0) }; var filesPanel = new Grid(); filesPanel.RowDefinitions.Add(new RowDefinition { Height = GridLength.Auto }); filesPanel.RowDefinitions.Add(new RowDefinition { Height = new GridLength(1, GridUnitType.Star) }); filesPanel.Children.Add(CreateDashboardHeader("backup", IsGerman ? "HERUNTERGELADENE DATEIEN" : "DOWNLOADED FILES", (Brush)FindResource("GoldBrush"))); _downloadedFilesPanel = new StackPanel { Margin = new Thickness(6, 10, 6, 6) }; var filesScroll = new ScrollViewer { Content = _downloadedFilesPanel, VerticalScrollBarVisibility = ScrollBarVisibility.Auto, HorizontalScrollBarVisibility = ScrollBarVisibility.Disabled, Background = (Brush)FindResource("SurfaceBrush") }; Grid.SetRow(filesScroll, 1); filesPanel.Children.Add(filesScroll); filesCard.Child = filesPanel; Grid.SetRow(filesCard, 1); right.Children.Add(filesCard); Grid.SetColumn(right, 1); root.Children.Add(right);
        var current = _service.DetectCurrent(); foreach (var p in GetDistinctPlugins()) { var active = current?.Sha256.Equals(p.Sha256, StringComparison.OrdinalIgnoreCase) == true; var b = new Button { Style = (Style)FindResource("TileButtonStyle"), BorderBrush = active ? (Brush)FindResource("SuccessBrush") : (Brush)FindResource("AccentBrush"), Margin = new Thickness(0, 2, 0, 2), Height = 58, HorizontalContentAlignment = HorizontalAlignment.Left, Content = new TextBlock { Text = active ? $"{p.DisplayName}   —   {Texts.Active.TrimEnd(':')}" : p.DisplayName, FontSize = 15, Foreground = active ? (Brush)FindResource("SuccessBrush") : (Brush)FindResource("ForegroundBrush") } }; b.Click += (_, _) => Activate(p); list.Children.Add(b); }
        PageHost.Content = root; SetGlobalStatus(status ?? (IsGerman ? "Bereit." : "Ready.")); _ = RefreshDownloadedFilesAsync();
    }

    private async Task RunUpdaterAsync()
    {
        if (_updaterCts is not null) return; _updaterCts = new CancellationTokenSource(); _updaterProgress!.Visibility = Visibility.Visible; _updaterProgress.Value = 0; _updaterStatus!.Text = IsGerman ? "Suche nach verfügbaren YACA Versionen …" : "Checking for available YACA versions …"; SetGlobalStatus(_updaterStatus.Text);
        var progress = new Progress<YacaUpdaterProgress>(p => { _updaterVersion!.Text = $"YACA {p.Version}"; _updaterStatus!.Text = p.Status; if (p.TotalBytes is > 0) _updaterProgress!.Value = Math.Min(100, p.BytesReceived * 100d / p.TotalBytes.Value); _updaterSize!.Text = p.TotalBytes is > 0 ? $"{p.BytesReceived / 1024d / 1024d:0.00} MB / {p.TotalBytes.Value / 1024d / 1024d:0.00} MB" : string.Empty; if (p.Completed && p.Success) SetGlobalStatus($"YACA {p.Version}: {p.Status}", true); else if (p.Completed && !p.Success) SetGlobalStatus($"YACA {p.Version}: {p.Status}"); });
        try { await _updater.DownloadMissingAsync(progress, _updaterCts.Token); await RefreshDownloadedFilesAsync(); ShowSwitchPage(IsGerman ? "YACA Downloads aktualisiert – neue Versionen stehen links zur Verfügung." : "YACA downloads refreshed – new versions are available on the left."); SetGlobalStatus(IsGerman ? "YACA Downloads aktualisiert." : "YACA downloads refreshed.", true); }
        catch (OperationCanceledException) { SetGlobalStatus(IsGerman ? "YACA Update abgebrochen." : "YACA update cancelled."); }
        catch (Exception ex) { _service.Logger.Error($"YACA updater failed: {ex}"); SetGlobalStatus(IsGerman ? "YACA Update fehlgeschlagen." : "YACA update failed."); }
        finally { _updaterCts.Dispose(); _updaterCts = null; }
    }

    private async Task RefreshDownloadedFilesAsync()
    {
        if (_downloadedFilesPanel is null) return; var files = await _updater.GetAvailableDownloadsAsync(); _downloadedFilesPanel.Children.Clear(); if (files.Count == 0) { _downloadedFilesPanel.Children.Add(new TextBlock { Text = IsGerman ? "Noch keine Downloads vorhanden." : "No downloads yet.", Foreground = (Brush)FindResource("SecondaryBrush"), FontSize = 14 }); return; }
        foreach (var file in files) { var row = new Grid { MinHeight = 38, Margin = new Thickness(0, 2, 0, 2) }; row.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) }); row.ColumnDefinitions.Add(new ColumnDefinition { Width = GridLength.Auto }); row.Children.Add(new TextBlock { Text = $"YACA {file.Version}", FontSize = 15, FontWeight = FontWeights.SemiBold, VerticalAlignment = VerticalAlignment.Center }); var size = new TextBlock { Text = $"{file.Size / 1024d / 1024d:0.00} MB", FontSize = 13, Foreground = (Brush)FindResource("SecondaryBrush"), VerticalAlignment = VerticalAlignment.Center }; Grid.SetColumn(size, 1); row.Children.Add(size); _downloadedFilesPanel.Children.Add(row); }
    }

    private void Activate(YacaPluginInfo plugin) { var text = Texts; var current = _service.DetectCurrent(); if (current?.Sha256.Equals(plugin.Sha256, StringComparison.OrdinalIgnoreCase) == true) { SetGlobalStatus(text.AlreadyActiveMessage); return; } if (_service.Settings.WarnIfTeamSpeakRunning && TeamSpeakDetector.IsRunning() && MessageBox.Show(text.TeamspeakRunningMessage, text.TeamspeakRunningTitle, MessageBoxButton.YesNo, MessageBoxImage.Warning) != MessageBoxResult.Yes) return; try { Mouse.OverrideCursor = Cursors.Wait; _service.Installer.Install(plugin, _service.TargetFile, current, _service.Settings.AutomaticBackup, _service.Settings.MaxBackups); ShowSwitchPage($"{plugin.DisplayName} {text.ActivatedMessage}"); } catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or InvalidDataException or InvalidOperationException or YacaOperationException) { _service.Logger.Error($"YACA switch failed: {ex}"); ShowError(Localization.GetErrorMessage(ex, text, text.ErrorUnexpected)); } finally { Mouse.OverrideCursor = null; } }
    private void CreateBackupFromDashboard() { var text = Texts; if (TeamSpeakDetector.IsRunning() && _service.Settings.WarnIfTeamSpeakRunning && MessageBox.Show(text.TeamspeakRunningMessage, text.TeamspeakRunningTitle, MessageBoxButton.YesNo, MessageBoxImage.Warning) != MessageBoxResult.Yes) return; try { var current = _service.DetectCurrent(); if (current is null) { ShowError(text.NotInstalled); return; } if (_service.Backups.CreateBackup(_service.TargetFile, current, automatic: false) is null) { ShowError(text.ErrorUnexpected); return; } _service.Backups.Trim(_service.Settings.MaxBackups); RefreshHome(); FlashElement(_backupCard); } catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or InvalidDataException or InvalidOperationException) { _service.Logger.Error($"Dashboard backup failed: {ex}"); ShowError(Localization.GetErrorMessage(ex, text, text.ErrorUnexpected)); } }

    private void CloseTeamSpeak() { var text = Texts; if (!TeamSpeakDetector.IsRunning()) { RefreshHome(); return; } if (MessageBox.Show(text.CloseTeamspeakQuestion, text.TeamspeakRunningTitle, MessageBoxButton.YesNo, MessageBoxImage.Warning) != MessageBoxResult.Yes) return; try { Mouse.OverrideCursor = Cursors.Wait; if (!TeamSpeakDetector.TryCloseWithElevation(TimeSpan.FromSeconds(10))) ShowError(text.CloseTeamspeakFailed); } catch (Exception ex) when (ex is InvalidOperationException or System.ComponentModel.Win32Exception) { ShowError(Localization.GetErrorMessage(ex, text, text.CloseTeamspeakFailed)); } finally { Mouse.OverrideCursor = null; RefreshHome(); } }
    private void ShowBackups() { _activePage = "backups"; SetActiveNav("backups"); PageHost.Content = new BackupView(_service, this); SetGlobalStatus(IsGerman ? "Backupverwaltung geöffnet." : "Backup management opened."); }
    private void ShowConfig() { _activePage = "config"; SetActiveNav("config"); PageHost.Content = new ConfigView(_service, this); SetGlobalStatus(IsGerman ? "Konfiguration geöffnet." : "Configuration opened."); }
    private void ShowInfo() { _activePage = "info"; SetActiveNav("info"); PageHost.Content = new InfoView(_service.Settings.Language); SetGlobalStatus(IsGerman ? "Info & Links geöffnet." : "Info & Links opened."); }
    private void ShowComingSoon() => ShowSwitchPage(IsGerman ? "Der YACA Updater ist in den Download-Bereich integriert." : "The YACA Updater is integrated into the download area.");
    internal void ReturnHome() => ShowHome();
    private void RefreshActivePage(bool announce) { if (_activePage == "home") RefreshHome(announce); else if (_activePage == "switch") ShowSwitchPage(); else if (_activePage == "backups") PageHost.Content = new BackupView(_service, this); else if (_activePage == "config") PageHost.Content = new ConfigView(_service, this); }
    private void ShowError(string message) => SetGlobalStatus(message);
    private void FlashElement(Border? element) { if (element is null) return; _flashTimer?.Stop(); var original = element.BorderBrush; element.BorderBrush = (Brush)FindResource("GoldBrush"); _flashTimer = new System.Windows.Threading.DispatcherTimer { Interval = TimeSpan.FromMilliseconds(650) }; _flashTimer.Tick += (_, _) => { element.BorderBrush = original; _flashTimer!.Stop(); }; _flashTimer.Start(); }
    private void TitleBar_MouseLeftButtonDown(object sender, MouseButtonEventArgs e) { if (e.ClickCount == 2) { WindowState = WindowState == WindowState.Maximized ? WindowState.Normal : WindowState.Maximized; return; } if (e.ChangedButton == MouseButton.Left) DragMove(); }
    private void Minimize_Click(object sender, RoutedEventArgs e) => WindowState = WindowState.Minimized;
    private void Maximize_Click(object sender, RoutedEventArgs e) => WindowState = WindowState == WindowState.Maximized ? WindowState.Normal : WindowState.Maximized;
    private void Close_Click(object sender, RoutedEventArgs e) { _updaterCts?.Cancel(); Close(); }
}