[CmdletBinding()]
param()
$ErrorActionPreference='Stop';$Root=Split-Path -Parent $PSScriptRoot
$required=@('YacaPluginSwitcher.sln','Directory.Build.props','src/YacaPluginSwitcher.Core/YacaPluginSwitcher.Core.csproj','src/YacaPluginSwitcher/YacaPluginSwitcher.csproj','src/YacaPluginSwitcher/App.xaml','src/YacaPluginSwitcher/App.xaml.cs','src/YacaPluginSwitcher/MainWindow.xaml','src/YacaPluginSwitcher/MainWindow.xaml.cs','src/YacaPluginSwitcher/StartupWindow.xaml','src/YacaPluginSwitcher/StartupWindow.xaml.cs','src/YacaPluginSwitcher/Styles/Colors.xaml','src/YacaPluginSwitcher/Styles/Controls.xaml','src/YacaPluginSwitcher/Views/BackupView.xaml','src/YacaPluginSwitcher/Views/BackupView.xaml.cs','src/YacaPluginSwitcher/Views/ConfigView.xaml','src/YacaPluginSwitcher/Views/ConfigView.xaml.cs','src/YacaPluginSwitcher/Views/InfoView.xaml','src/YacaPluginSwitcher/Views/InfoView.xaml.cs')
foreach($r in $required){if(-not(Test-Path (Join-Path $Root $r)-PathType Leaf)){throw "Required file missing: $r"}}
foreach($p in Get-ChildItem $Root -Recurse -File -Include *.csproj,*.props,*.pubxml){[xml]$null=Get-Content $p.FullName -Raw}
foreach($f in Get-ChildItem $Root -Recurse -File -Filter *.cs){$t=Get-Content $f.FullName -Raw;if($t-match '(?i)<PackageReference|Newtonsoft|MahApps|MaterialDesign'){throw "External dependency marker found: $($f.FullName)"};if($t-match 'System\.Windows\.Forms|System\.Drawing|namespace YacaPluginSwitcher\.UI'){throw "Legacy WinForms/UI reference remains: $($f.FullName)"}}
$project=Get-Content(Join-Path $Root 'src/YacaPluginSwitcher/YacaPluginSwitcher.csproj')-Raw
foreach($s in @('<TargetFramework>net10.0-windows</TargetFramework>','<UseWPF>true</UseWPF>','<SelfContained>true</SelfContained>','<PublishSingleFile>true</PublishSingleFile>','<DebugSymbols>false</DebugSymbols>','<DebugType>None</DebugType>')){if($project -notmatch [regex]::Escape($s)){throw "Project setting missing: $s"}}
if($project -match 'UseWindowsForms|WinForms|WindowsForms'){throw 'WPF project must not enable WinForms.'}
$main=Get-Content(Join-Path $Root 'src/YacaPluginSwitcher/MainWindow.xaml')-Raw;$code=Get-Content(Join-Path $Root 'src/YacaPluginSwitcher/MainWindow.xaml.cs')-Raw
foreach($t in @('YACA','PLUGIN SWITCHER','Sprache','Dashboard')){if($main -notmatch [regex]::Escape($t) -and $code -notmatch [regex]::Escape($t)){throw "WPF UI/reference missing: $t"}}
foreach($event in @('LanguageCombo_SelectionChanged','Minimize_Click','Maximize_Click','Close_Click')){if($main -match [regex]::Escape($event) -and $code -notmatch ('(?m)\b'+$event+'\s*\(')){throw "WPF event handler missing: $event"}}
if($main -notmatch 'x:Name="NavPanel"'){throw 'WPF navigation host missing.'};if($main -notmatch 'x:Name="PageHost"'){throw 'WPF page host missing.'};if($code -notmatch '(?m)\bAddNav\s*\('){throw 'WPF navigation builder missing.'};if($code -notmatch '(?m)\bAddTile\s*\('){throw 'WPF dashboard tile builder missing.'}
if($main-notmatch '258'){throw 'Sidebar width must remain 258 px for the reference layout.'};if($main-notmatch '1536'-or$main-notmatch '1024'){throw 'Reference window size 1536x1024 missing.'};if($main-notmatch 'WindowStyle="None"'-or$main-notmatch 'WindowChrome'){throw 'Custom dark title bar/window chrome missing.'};if($code-match 'ProfessionalMainForm|ProfessionalVisuals|Theme\.|DarkMode\.'){throw 'Legacy renderer remains in MainWindow.'}
$app=Get-Content(Join-Path $Root 'src/YacaPluginSwitcher/App.xaml')-Raw;if($app-notmatch 'Styles/Colors.xaml'-or$app-notmatch 'Styles/Controls.xaml'){throw 'WPF resource dictionaries are not merged.'};$appc=Get-Content(Join-Path $Root 'src/YacaPluginSwitcher/App.xaml.cs')-Raw;if($appc-notmatch 'new StartupWindow\(\)'){throw 'WPF startup window is not opened by App.'}
$info=Get-Content(Join-Path $Root 'src/YacaPluginSwitcher/Views/InfoView.xaml.cs')-Raw;if($info-notmatch 'YacaLinks'-or$info-notmatch 'TsLinks'){throw 'Info link collections missing.'}
$appPaths=Get-Content(Join-Path $Root 'src/YacaPluginSwitcher.Core/AppPaths.cs')-Raw;if($appPaths-match 'LocalApplicationData|ApplicationData'){throw 'Portable paths must not use APPDATA or LOCALAPPDATA.'};if($appPaths-notmatch 'SettingsFilePath\s*=\s*Path\.Combine\(BaseDirectory,\s*"config\.json"\)'){throw 'config.json must be stored beside executable.'}
Write-Host 'Static preflight: PASS' -ForegroundColor Green