[CmdletBinding()]
param()
$ErrorActionPreference='Stop';$Root=Split-Path -Parent $PSScriptRoot
$required=@('YacaPluginSwitcher.sln','Directory.Build.props','src/YacaPluginSwitcher.Core/YacaPluginSwitcher.Core.csproj','src/YacaPluginSwitcher/YacaPluginSwitcher.csproj','src/YacaPluginSwitcher/App.xaml','src/YacaPluginSwitcher/App.xaml.cs','src/YacaPluginSwitcher/MainWindow.xaml','src/YacaPluginSwitcher/MainWindow.xaml.cs','src/YacaPluginSwitcher/StartupWindow.xaml','src/YacaPluginSwitcher/StartupWindow.xaml.cs','src/YacaPluginSwitcher/Styles/Colors.xaml','src/YacaPluginSwitcher/Styles/Controls.xaml','src/YacaPluginSwitcher/Views/BackupView.xaml','src/YacaPluginSwitcher/Views/BackupView.xaml.cs','src/YacaPluginSwitcher/Views/ConfigView.xaml','src/YacaPluginSwitcher/Views/ConfigView.xaml.cs','src/YacaPluginSwitcher/Views/InfoView.xaml','src/YacaPluginSwitcher/Views/InfoView.xaml.cs')
foreach($r in $required){if(-not(Test-Path (Join-Path $Root $r)-PathType Leaf)){throw "Required file missing: $r"}}
foreach($p in Get-ChildItem $Root -Recurse -File -Include *.csproj,*.props,*.pubxml){[xml]$null=Get-Content $p.FullName -Raw}
foreach($f in Get-ChildItem $Root -Recurse -File -Filter *.cs){$t=Get-Content $f.FullName -Raw;if($t-match '(?i)<PackageReference|Newtonsoft|MahApps|MaterialDesign'){throw "External dependency marker found: $($f.FullName)"};if(([regex]::Matches($t,'\{')).Count-ne([regex]::Matches($t,'\}')).Count){throw "Brace count mismatch: $($f.FullName)"};if($t-match 'System\.Windows\.Forms|System\.Drawing|namespace YacaPluginSwitcher\.UI'){throw "Legacy WinForms/UI reference remains: $($f.FullName)"}}
$project=Get-Content(Join-Path $Root 'src/YacaPluginSwitcher/YacaPluginSwitcher.csproj')-Raw
foreach($s in @('<TargetFramework>net10.0-windows</TargetFramework>','<UseWPF>true</UseWPF>','<SelfContained>true</SelfContained>','<PublishSingleFile>true</PublishSingleFile>','<DebugSymbols>false</DebugSymbols>','<DebugType>None</DebugType>')){if($project -notmatch [regex]::Escape($s)){throw "Project setting missing: $s"}}
if($project -match 'UseWindowsForms|WinForms|WindowsForms'){throw 'WPF project must not enable WinForms.'}
foreach($r in @('Assets\yaca_logo.png','Assets\discord_icon.png','Assets\github_icon.png')){if(-not(Test-Path (Join-Path $Root "src/YacaPluginSwitcher/$r")-PathType Leaf)){throw "Required UI asset missing: $r"};if($project -notmatch ('<Resource Include="'+[regex]::Escape($r)+'" />')){throw "WPF UI asset is not a Resource: $r"}}
$main=Get-Content(Join-Path $Root 'src/YacaPluginSwitcher/MainWindow.xaml')-Raw;$code=Get-Content(Join-Path $Root 'src/YacaPluginSwitcher/MainWindow.xaml.cs')-Raw
foreach($t in @('YACA','PLUGIN SWITCHER','YACA WECHSELN','BACKUP ERSTELLEN','YACA UPDATER','TEAMSpeak 3 STATUS','Sprache','Dashboard','ShowSwitchPage','ShowBackups','ShowConfig','ShowInfo','CloseTeamSpeak','CreateBackupFromDashboard')){if($main -notmatch [regex]::Escape($t)-and$code -notmatch [regex]::Escape($t)){throw "WPF UI/reference missing: $t"}}
if($main-notmatch '258'){throw 'Sidebar width must remain 258 px for the reference layout.'};if($main-notmatch '1536'-or$main-notmatch '1024'){throw 'Reference window size 1536x1024 missing.'};if($main-notmatch 'WindowStyle="None"'-or$main-notmatch 'WindowChrome'){throw 'Custom dark title bar/window chrome missing.'};if($code-match 'ProfessionalMainForm|ProfessionalVisuals|Theme\.|DarkMode\.'){throw 'Legacy renderer remains in MainWindow.'}
$app=Get-Content(Join-Path $Root 'src/YacaPluginSwitcher/App.xaml')-Raw;if($app-notmatch 'Styles/Colors.xaml'-or$app-notmatch 'Styles/Controls.xaml'){throw 'WPF resource dictionaries are not merged.'};$appc=Get-Content(Join-Path $Root 'src/YacaPluginSwitcher/App.xaml.cs')-Raw;if($appc-notmatch 'new StartupWindow\(\)'){throw 'WPF startup window is not opened by App.'}
$backup=Get-Content(Join-Path $Root 'src/YacaPluginSwitcher/Views/BackupView.xaml.cs')-Raw;foreach($t in @('SelectableBackupsForDeletion','DeleteBackups','Restore','Sha256','TeamSpeakDetector')){if($backup-notmatch $t){throw "Backup workflow missing: $t"}}
$config=Get-Content(Join-Path $Root 'src/YacaPluginSwitcher/Views/ConfigView.xaml.cs')-Raw;foreach($t in @('TeamSpeakPluginDirectories','MultipleTeamSpeakInstances','MaxBackups','AutomaticBackup','WarnIfTeamSpeakRunning','GeneralLogging','DebugLogging','SelectableBackups','OpenFolderDialog')){if($config-notmatch $t){throw "Configuration workflow missing: $t"}}
$info=Get-Content(Join-Path $Root 'src/YacaPluginSwitcher/Views/InfoView.xaml.cs')-Raw;foreach($t in @('YacaLinks','TsLinks','discord.yaca.systems','downloads','github.com/ViP3R76/Yaca-Plugin-Switcher','Process.Start')){if($info-notmatch $t){throw "Info/link workflow missing: $t"}}
$appPaths=Get-Content(Join-Path $Root 'src/YacaPluginSwitcher.Core/AppPaths.cs')-Raw;if($appPaths-match 'LocalApplicationData|ApplicationData'){throw 'Portable paths must not use APPDATA or LOCALAPPDATA.'};if($appPaths-notmatch 'SettingsFilePath\s*=\s*Path\.Combine\(BaseDirectory,\s*"config\.json"\)'){throw 'config.json must be stored beside executable.'};if($appPaths-notmatch 'LogDirectory\s*=\s*Path\.Combine\(BaseDirectory,\s*"Logs"\)'){throw 'Logs must be stored beside executable.'};if($appPaths-notmatch 'BackupDirectory\s*=\s*Path\.Combine\(BaseDirectory,\s*"Backups"\)'){throw 'Backups must be stored beside executable.'}
$legacy=Get-ChildItem (Join-Path $Root 'src/YacaPluginSwitcher') -Recurse -File | Where-Object { $_.FullName -match '\\(MainForm|ProfessionalMainForm|StartupForm)\.cs$|\\UI\\' };if($legacy){throw "Legacy WinForms UI files remain: $($legacy.FullName -join ', ')"}
$tests=Get-ChildItem $Root -Recurse -File|Where-Object{$_.FullName-match '\\tests\\|Test\.csproj$|Tests\.dll$'};if($tests){throw 'Test projects/artifacts must not be part of release source.'}
Write-Host 'Static preflight: PASS' -ForegroundColor Green;Write-Host 'WPF UI/reference sanity: PASS' -ForegroundColor Green;Write-Host 'UI asset/resource validation: PASS' -ForegroundColor Green;Write-Host 'Run dotnet build on Windows with the .NET 10 SDK for compiler/XAML/analyzer validation.' -ForegroundColor Yellow